import 'package:flutter/material.dart';
import 'package:shop/models/most.wanted.model.dart';

class MostWantedRepository {
  static List<MostWantedModel> mostWanteds = [
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      2100,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.red,
      'assets/images/jordan-1-mid.png',
      'Jordan 1 Mid',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      1980,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.blue[900],
      'assets/images/air-jordan-1-acclimate.png',
      'Air Jordan 1 Acclimate',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      2500,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.yellow[800],
      'assets/images/air-jordan-1-zoom-confort.png',
      'Air Jordan 1 Zoom Confort',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      2220,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.green[800],
      'assets/images/air-jordan-1-mid-se-red.png',
      'Air Jordan 1 Mid SE Red',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      1920,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.yellow,
      'assets/images/air-jordan-1-mid.png',
      'Air Jordan 1 Mid',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      1990,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.limeAccent[600],
      'assets/images/air-jordan-1-retro-high-og.png',
      'Air Jordan 1 Retro High OG',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
    MostWantedModel(
      '700676ca-61f8-477f-98c9-95fe0c687766',
      1999,
      'Jordan',
      ['38', '39', '40', '41'],
      Colors.blue[900],
      'assets/images/air-jordan-1-mid-se.png',
      'Air Jordan 1 Mid SE',
      'Exercitation reprehenderit culpa minim dolore non velit. Aliquip sunt excepteur quis do esse et magna aliquip reprehenderit quis anim eu qui laboris. Reprehenderit irure nisi eiusmod minim quis esse ea.',
    ),
  ];
}
